[package]
name = "megadb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]
config = "0.15.13"
rand = "0.9.2"
serde = "1.0.219"
tokio = { version = "1", features = ["full"] }
